import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/main-nav";
import { getDB } from "@/lib/db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const db = await getDB();
  const { userCount, promptCount, maliciousPromptRate } = db.config;


  return (
    <html lang="en">
      <body className={inter.className}>
        <MainNav defaultUserCount={userCount} defaultPromptCount={promptCount} defaultMaliciousPromptRate={maliciousPromptRate} />
        <main className="max-w-screen-xl mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
